[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-github"
  version = "v1.3.0"

  [constraint.metadata]
    govendor-exclude-prefixes = ["github.com/golang/protobuf"]
    govendor-override = true

# NOTE: the following overrides were injected by govendor-override. It may be necessary to
# remove some of these overrides in order to produce a buildable vendor tree.
[[override]]
  name = "github.com/agext/levenshtein"
  version = "=v1.2.1"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "2bd8b58cf4275aeb086ade613de226773e29e853"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.13.47"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/speakeasy"
  version = "=v0.1.0"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/blang/semver"
  revision = "4a1e882c79dcf4ec00d2e29fac74b9c8938d5052"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/davecgh/go-spew"
  version = "=v1.1.0"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/go-ini/ini"
  version = "=v1.36.0"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/google/go-github"
  version = "=v16.0.0"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/google/go-querystring"
  revision = "53e6ce116135b80d037921a7fdd5138cf32d7a8a"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "06c9ea3a335b7443026f8124b22619524420291b"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-getter"
  revision = "90bb99a48d86cf1d327cee9968f7428f90ba13c1"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "b4e5765d1e5f00a0550911084f45f8214b5b83b9"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "e53f54cbf51efde642d4711313e829a1ff0c236d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-safetemp"
  revision = "b1a1dbde6fdc11e3ae79efd9039009e22d4ae240"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "4fe82ae3040f80a03d04d2cccb5606a626b8e1ee"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "5f8ed954abd873b2c09616ba0aa607892bbca7e9"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "fa9f258a92500514cc8e9c67020487709df92432"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "=v0.11.7"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "2658be15c5f05e76244154714161f17e3e77de2e"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "0b12d6b5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/kylelemons/godebug"
  revision = "d65d576e9348f5982d7f6d83682b694e731a45c6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mattn/go-isatty"
  revision = "6ca4dbf54d38eea1a992b3c722a76a5d1c4cb25c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/cli"
  revision = "b068abc08c994321eafd9fd500d0704cb6defcb1"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "a61a99592b77c9ba629d254a693acffaeb4b7e28"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/hashstructure"
  revision = "2bca23e0e452137f789efbc8610126fd8b94f73b"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "00c29f56e2386353d58c599509e8dc3801b0d716"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/oklog/run"
  revision = "6934b124db28979da51d3470dadfa34d73d72652"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/posener/complete"
  version = "=v1.1.1"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/terraform-providers/terraform-provider-tls"
  version = "=v1.1.0"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/ulikunitz/xz"
  version = "=v0.5.4"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "d006e4534bc4fbc512383aa98d04d641ea951ba5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/crypto"
  revision = "12892e8c234f4fe6f6803f052061de9057903bb2"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/net"
  revision = "f73e4c9ed3b7ebdd5f699a16a880c2b1994e50dd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/oauth2"
  revision = "cdc340f7c179dbbfa4afd43b7614e8fcadde4269"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/sys"
  revision = "378d26f46672a356c46195c28f61bdb4c0a781dd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/text"
  revision = "ece95c760240037f89ebcbdd7155ac8cb52e38fa"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/appengine"
  version = "=v1.0.0"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/genproto"
  revision = "86e600f69ee4704c6efbf6a2a40a5c10700e76c2"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/grpc"
  revision = "45d7f3a23f0b937ba711aa0e3e3426325d3b9ae4"
  [override.metadata]
    govendor-overridden=true
