// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IssueLabel extends pulumi.CustomResource {
    /**
     * Get an existing IssueLabel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IssueLabelState, opts?: pulumi.CustomResourceOptions): IssueLabel {
        return new IssueLabel(name, <any>state, { ...opts, id: id });
    }

    public readonly color: pulumi.Output<string>;
    public readonly description: pulumi.Output<string | undefined>;
    public /*out*/ readonly etag: pulumi.Output<string>;
    public readonly name: pulumi.Output<string>;
    public readonly repository: pulumi.Output<string>;
    public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a IssueLabel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IssueLabelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IssueLabelArgs | IssueLabelState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: IssueLabelState = argsOrState as IssueLabelState | undefined;
            inputs["color"] = state ? state.color : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["etag"] = state ? state.etag : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["repository"] = state ? state.repository : undefined;
            inputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as IssueLabelArgs | undefined;
            if (!args || args.color === undefined) {
                throw new Error("Missing required property 'color'");
            }
            if (!args || args.name === undefined) {
                throw new Error("Missing required property 'name'");
            }
            if (!args || args.repository === undefined) {
                throw new Error("Missing required property 'repository'");
            }
            inputs["color"] = args ? args.color : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["repository"] = args ? args.repository : undefined;
            inputs["etag"] = undefined /*out*/;
            inputs["url"] = undefined /*out*/;
        }
        super("github:index/issueLabel:IssueLabel", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IssueLabel resources.
 */
export interface IssueLabelState {
    readonly color?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly etag?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly repository?: pulumi.Input<string>;
    readonly url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IssueLabel resource.
 */
export interface IssueLabelArgs {
    readonly color: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly name: pulumi.Input<string>;
    readonly repository: pulumi.Input<string>;
}
