// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Team extends pulumi.CustomResource {
    /**
     * Get an existing Team resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamState, opts?: pulumi.CustomResourceOptions): Team {
        return new Team(name, <any>state, { ...opts, id: id });
    }

    public readonly description: pulumi.Output<string | undefined>;
    public /*out*/ readonly etag: pulumi.Output<string>;
    public readonly ldapDn: pulumi.Output<string | undefined>;
    public readonly name: pulumi.Output<string>;
    public readonly parentTeamId: pulumi.Output<number | undefined>;
    public readonly privacy: pulumi.Output<string | undefined>;
    public /*out*/ readonly slug: pulumi.Output<string>;

    /**
     * Create a Team resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamArgs | TeamState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: TeamState = argsOrState as TeamState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["etag"] = state ? state.etag : undefined;
            inputs["ldapDn"] = state ? state.ldapDn : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["parentTeamId"] = state ? state.parentTeamId : undefined;
            inputs["privacy"] = state ? state.privacy : undefined;
            inputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as TeamArgs | undefined;
            if (!args || args.name === undefined) {
                throw new Error("Missing required property 'name'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["ldapDn"] = args ? args.ldapDn : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["parentTeamId"] = args ? args.parentTeamId : undefined;
            inputs["privacy"] = args ? args.privacy : undefined;
            inputs["etag"] = undefined /*out*/;
            inputs["slug"] = undefined /*out*/;
        }
        super("github:index/team:Team", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Team resources.
 */
export interface TeamState {
    readonly description?: pulumi.Input<string>;
    readonly etag?: pulumi.Input<string>;
    readonly ldapDn?: pulumi.Input<string>;
    readonly name?: pulumi.Input<string>;
    readonly parentTeamId?: pulumi.Input<number>;
    readonly privacy?: pulumi.Input<string>;
    readonly slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Team resource.
 */
export interface TeamArgs {
    readonly description?: pulumi.Input<string>;
    readonly ldapDn?: pulumi.Input<string>;
    readonly name: pulumi.Input<string>;
    readonly parentTeamId?: pulumi.Input<number>;
    readonly privacy?: pulumi.Input<string>;
}
