// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TeamRepository extends pulumi.CustomResource {
    /**
     * Get an existing TeamRepository resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamRepositoryState, opts?: pulumi.CustomResourceOptions): TeamRepository {
        return new TeamRepository(name, <any>state, { ...opts, id: id });
    }

    public /*out*/ readonly etag: pulumi.Output<string>;
    public readonly permission: pulumi.Output<string | undefined>;
    public readonly repository: pulumi.Output<string>;
    public readonly teamId: pulumi.Output<string>;

    /**
     * Create a TeamRepository resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeamRepositoryArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamRepositoryArgs | TeamRepositoryState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: TeamRepositoryState = argsOrState as TeamRepositoryState | undefined;
            inputs["etag"] = state ? state.etag : undefined;
            inputs["permission"] = state ? state.permission : undefined;
            inputs["repository"] = state ? state.repository : undefined;
            inputs["teamId"] = state ? state.teamId : undefined;
        } else {
            const args = argsOrState as TeamRepositoryArgs | undefined;
            if (!args || args.repository === undefined) {
                throw new Error("Missing required property 'repository'");
            }
            if (!args || args.teamId === undefined) {
                throw new Error("Missing required property 'teamId'");
            }
            inputs["permission"] = args ? args.permission : undefined;
            inputs["repository"] = args ? args.repository : undefined;
            inputs["teamId"] = args ? args.teamId : undefined;
            inputs["etag"] = undefined /*out*/;
        }
        super("github:index/teamRepository:TeamRepository", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TeamRepository resources.
 */
export interface TeamRepositoryState {
    readonly etag?: pulumi.Input<string>;
    readonly permission?: pulumi.Input<string>;
    readonly repository?: pulumi.Input<string>;
    readonly teamId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TeamRepository resource.
 */
export interface TeamRepositoryArgs {
    readonly permission?: pulumi.Input<string>;
    readonly repository: pulumi.Input<string>;
    readonly teamId: pulumi.Input<string>;
}
