// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class UserGpgKey extends pulumi.CustomResource {
    /**
     * Get an existing UserGpgKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserGpgKeyState, opts?: pulumi.CustomResourceOptions): UserGpgKey {
        return new UserGpgKey(name, <any>state, { ...opts, id: id });
    }

    public readonly armoredPublicKey: pulumi.Output<string>;
    public /*out*/ readonly etag: pulumi.Output<string>;
    public /*out*/ readonly keyId: pulumi.Output<string>;

    /**
     * Create a UserGpgKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserGpgKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserGpgKeyArgs | UserGpgKeyState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: UserGpgKeyState = argsOrState as UserGpgKeyState | undefined;
            inputs["armoredPublicKey"] = state ? state.armoredPublicKey : undefined;
            inputs["etag"] = state ? state.etag : undefined;
            inputs["keyId"] = state ? state.keyId : undefined;
        } else {
            const args = argsOrState as UserGpgKeyArgs | undefined;
            if (!args || args.armoredPublicKey === undefined) {
                throw new Error("Missing required property 'armoredPublicKey'");
            }
            inputs["armoredPublicKey"] = args ? args.armoredPublicKey : undefined;
            inputs["etag"] = undefined /*out*/;
            inputs["keyId"] = undefined /*out*/;
        }
        super("github:index/userGpgKey:UserGpgKey", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UserGpgKey resources.
 */
export interface UserGpgKeyState {
    readonly armoredPublicKey?: pulumi.Input<string>;
    readonly etag?: pulumi.Input<string>;
    readonly keyId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a UserGpgKey resource.
 */
export interface UserGpgKeyArgs {
    readonly armoredPublicKey: pulumi.Input<string>;
}
