// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class UserSshKey extends pulumi.CustomResource {
    /**
     * Get an existing UserSshKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserSshKeyState, opts?: pulumi.CustomResourceOptions): UserSshKey {
        return new UserSshKey(name, <any>state, { ...opts, id: id });
    }

    public /*out*/ readonly etag: pulumi.Output<string>;
    public readonly key: pulumi.Output<string>;
    public readonly title: pulumi.Output<string>;
    public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a UserSshKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserSshKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserSshKeyArgs | UserSshKeyState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: UserSshKeyState = argsOrState as UserSshKeyState | undefined;
            inputs["etag"] = state ? state.etag : undefined;
            inputs["key"] = state ? state.key : undefined;
            inputs["title"] = state ? state.title : undefined;
            inputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as UserSshKeyArgs | undefined;
            if (!args || args.key === undefined) {
                throw new Error("Missing required property 'key'");
            }
            if (!args || args.title === undefined) {
                throw new Error("Missing required property 'title'");
            }
            inputs["key"] = args ? args.key : undefined;
            inputs["title"] = args ? args.title : undefined;
            inputs["etag"] = undefined /*out*/;
            inputs["url"] = undefined /*out*/;
        }
        super("github:index/userSshKey:UserSshKey", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UserSshKey resources.
 */
export interface UserSshKeyState {
    readonly etag?: pulumi.Input<string>;
    readonly key?: pulumi.Input<string>;
    readonly title?: pulumi.Input<string>;
    readonly url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a UserSshKey resource.
 */
export interface UserSshKeyArgs {
    readonly key: pulumi.Input<string>;
    readonly title: pulumi.Input<string>;
}
